version: '3.7'

networks:
  statamic:
    driver: bridge

services:
  statamic:
    image: ghcr.io/o1y/statamic-starter:latest-php7.4
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./statamic:/app
    networks:
      - statamic
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    networks:
      - statamic
  redis:
    image: redis:alpine
    networks:
      - statamic

volumes:
  data:
